#   商用程式設計

#        第一章

# 加法

In [5]:
a=3
b=5
a+b

8

# 網頁擷取程式

In [4]:
import requests
a=requests.get("http://www.must.edu.tw/")
print(a.text)

<!DOCTYPE html>
<!--
Template Name:明新科技大學
Author: <a href="http://www.os-templates.com/">OS Templates</a>
Author URI: http://www.os-templates.com/
Licence: Free to use under our free template licence terms
Licence URI: http://www.os-templates.com/template-terms
-->
<html>
<head>
<meta name="google-site-verification" content="qyA7Hl8GH4fSuN63aOHw_YOR_OiuioN_OJBIsW0AJTM" />
<title>明新科技大學</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name= " Accessible_website " content= " 本網站通過第(1)優先等級無障礙網頁檢測 " >
<link href="layout/styles/layout.css" rel="stylesheet" type="text/css" media="all">
<script type="text/javascript" src="layout/scripts/away.js"></script>
<script charset="UTF-8" type="text/javascript" src="http://webs.must.edu.tw/pagecount/showpage.php?page=must_school&show=no

# 第二章

# 單行註解

In [8]:
#單行註解
a=3
b=5
a+b

8

# 多行註解

In [9]:
'''
多行註解
'''
a=3
b=5
a+b

8

# 變數的設定

In [10]:
x=1

# 印出來

In [6]:
x,y,z = 3,6,9
print(x)
print(y)
print(z)

3
6
9


# 一般的加 乘 次方

In [3]:
x,y,z = 3,6,9
x += 1      
y *= 5      
z **=6      
print(x,y,z)

4 30 531441


# 傳回輸入數值的平方根

In [4]:
import math
a,b,c=3,4,5
s=(a+b+c)/2
d=math.sqrt(s*(s-a)*(s-b)*(s-c))
print(d)

6.0


# 傳回值

In [5]:
x=254
print(type(x))
id(x)
  

<class 'int'>


140709118595824

# 傳回值2

In [6]:
x='write'
print(type(x))
id(x)


<class 'str'>


1859646025944

# 求圓錐體面積

In [1]:
#半徑為4.5，el 高度為4.5的圓錐體面積為何?
import math
print((4.5*4.5*math.pi*4.5)/3)

95.42587685278995


# 一般的除法以及求商跟餘數

In [2]:
x=16
y=3
print(x/y)
print(x//y) 
print(x%y)  

5.333333333333333
5
1


# 關係運算

In [4]:
x=10
print(20==20)
y=20
print(x==y)
x=y
print(x)

True
False
20


# 判斷是否為真

In [5]:
a,b,c=10,20,30
print(a<=b<=c)

True


# 減法

In [6]:
x=3.141592627
print(x-3.14)

0.0015926269999999576


# 判斷是否為真2

In [7]:
y=2010
print(y%4==0 and y%100!=0 or y%400==0)
y=2012
print(y%4==0 and y%100!=0 or y%400==0)
y=2000
print(y%4==0 and y%100!=0 or y%400==0)

False
True
True


# 型態轉換

In [11]:
x=12
y=float(x)+0.5
print(y)
print(int('123'))
print(float('123'))
print(int(123.333))
x=10*3.25              #3.25
y=200*200              #40000
s='The value of x is ' + str(x) + 'and y is ' + str(y)
s1='The value of x is ' + repr(x) + 'and y is ' + repr(y)
print(s)
print(s1)

12.5
123
123.0
123
The value of x is 32.5and y is 40000
The value of x is 32.5and y is 40000


# 圓周率、求2的3次方、平方根

In [12]:
import math
print(math.pi)
print(math.pow(2,3))
print(8.3*10.58*math.sin(37.0/180*math.pi)/2)
print(math.sqrt(25))

3.141592653589793
8.0
26.423892221536985
5.0


# 輸入半徑後求圓面積

In [7]:
import math
r= input("請輸入半徑:")
area = float(r) * float(r) *math.pi
print("圓面積為:" ,area)

請輸入半徑:4.5
圓面積為: 63.61725123519331


# 第三章

# List串列

In [1]:
my_list0 = [1,2,3]
print(my_list0)
my_list1 = ['python' ,'js','SQL']
print(my_list1[0])
my_list1.append('java')
print(my_list1)
    

[1, 2, 3]
python
['python', 'js', 'SQL', 'java']


# 新增到特殊位置

In [2]:
my_list1.insert(0,'c#')
print(my_list1)
print(len(my_list1))

['c#', 'python', 'js', 'SQL', 'java']
5


# list長度

In [3]:
my_list2=['c#','python' ,'js','SQL','java']
print(len(my_list2))
print(len(my_list2[1]))

5
6


# 刪除某特定物件、某特定位置的物件、-1指的是從最後數來第一個位置

In [4]:
my_list3=['c#','python' ,'js','SQL','java']
my_list3.remove('js')    #刪除某特定物件
print(my_list3)
del my_list3[0]          #刪除某特定位置的物件
print(my_list3)
del my_list3[-1]         #-1指的是從最後數來第一個位置
print(my_list3)

['c#', 'python', 'SQL', 'java']
['python', 'SQL', 'java']
['python', 'SQL']


# 檢查是否存在

In [5]:
print('java' in['python' ,'js','SQL'])

False


# 串列的重複

In [7]:
a=[1,2]
print(a*5)

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]


# #串列取值

In [12]:
a=[1,2,3,4,5,6,7,8,9]
b=a[0:3]         #包含0，但是不包含3
print(b)
c=a[0:9:2]       #間隔取值 [開始:結束:間隔]
print(c)
del a[7:9]
print(a)
print(max(a))     #最大值
print(min(a))     #最小值
print(a.index(1))
print(a.count(1))

[1, 2, 3]
[1, 3, 5, 7, 9]
[1, 2, 3, 4, 5, 6, 7]
7
1
0
1


# 串列反轉跟串列排序

In [9]:
print(a)
a.reverse()   
print(a)
a.sort()    
print(a)

[1, 2, 3, 4, 5, 6, 7]
[7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7]


# 取特定位置的值

In [11]:
a=[123,'abc',[111,222],[333,444]]
print(a[0])
print(a[1])
print(a[2])
print(a[2][1])

123
abc
[111, 222]
222


# 不同的字串相加

In [13]:
a=[111,222] + [333,444] + [4156,1546]
print(a)

[111, 222, 333, 444, 4156, 1546]


# 串列List常用在For迴圈

In [15]:
shoplist = ['milk','egg','coffee','banana']
for item in shoplist:
    print(item)

milk
egg
coffee
banana


# tupe的元素不可新增刪除或修改

In [1]:
a_list=['python' ,'js','SQL']
a_tuple=('python' ,'js','SQL')
b_tuple=tuple(a_list)
print(type(a_list))
print(type(a_tuple))
print(b_tuple)

<class 'list'>
<class 'tuple'>
('python', 'js', 'SQL')


# 判斷類型

In [2]:
c_tuple= 111,333,222   #c_tuple=(111,2222,333)
print(c_tuple)
print(type(c_tuple))

(111, 333, 222)
<class 'tuple'>


# dict(字典-dictiontry)

# 帶有鍵值(key)的list

In [6]:
a_list=['python', 'js', 'c#']
a_dict={0:'python', 1:'js', 2:'c#'}
print(a_list[0])
print(a_dict[0])
b_dict={'1st':'python', '2nd':'js','3rd':'c#'}
print(b_dict['1st'])

python
python
python


# 第三章 流程控制

# 溫度

In [4]:
celsius=float(input('請輸入攝氏溫度'))
print(type(celsius))
fahrenheit=(9/5) * celsius + 32
print('華氏溫度',fahrenheit)

請輸入攝氏溫度20
<class 'float'>
華氏溫度 68.0


# 基本應用

In [6]:
import statistics as st
sample=[5,8,9,6,4,1,2,3,5,6]
print('樣本=',sample)
print('平均數=',st.mean(sample))
print('最大數=',max(sample))
print('最小數=',min(sample))
print('變異數=',round(st.variance(sample),2))
print('標準差=',round(st.stdev(sample),2))

樣本= [5, 8, 9, 6, 4, 1, 2, 3, 5, 6]
平均數= 4.9
最大數= 9
最小數= 1
變異數= 6.32
標準差= 2.51


# if

In [17]:
numA = 3
numB = 4
if numA < numB:
    print('numB是比較大的數')

numB是比較大的數


# 比較大小ex1

In [20]:
numA =int(input('請輸入numA:'))
numB =int(input('請輸入numB:'))
if numA <numB:
    print('numB是比較大的數')
else:
    print('numA是比較大的數')

請輸入numA:4
請輸入numB:5
numB是比較大的數


# 比較大小ex2

In [ ]:
numA =int(input('請輸入numA:'))
numB =int(input('請輸入numB:'))
if numA <numB:
    print('numB是比較大的數')
elif:
    print('numA是比較大的數')
else:
    print('numA跟numB相同大小')

# For迴圈

In [25]:
sum = 0
for i in range(1, 11):
    sum = sum + i
print('總和:', sum)

總和: 55


# 總和

In [26]:
sample=[2,1,4,8,3,2,6,5,9,7]
sum=0
for i in sample:
    sum=sum+i
print('總和:',sum)

總和: 47


# In-class exercise 隨堂練習

雞兔同籠問題進行求解。若共有35個頭，94隻腳，問共有幾隻雞?幾隻兔子?

In [27]:
head=35
leg =94
for rabbit in range(0, head+1):
    chicken=head-rabbit
    if((rabbit*4 +chicken*2)==leg):
        print('雞有',chicken,'隻')
        print('兔有',rabbit,'隻')

雞有 23 隻
兔有 12 隻


# 印字

In [28]:
mylist='I Iove Avenger IV'
for character in mylist:
    print(character)

I
 
I
o
v
e
 
A
v
e
n
g
e
r
 
I
V


# while迴圈

1+2+3+...+10的總和

In [1]:
sum = 0
count = 1
while count <= 10:
    sum = sum +count # sum += count
    count += 1 # count = count +1
print('1+2+3+...+10=',sum)

1+2+3+...+10= 55


# 銀行利息範例

In [2]:
x = 10000
year = 0
while x < 20000:
    year += 1
    x = x * 1.0104
print(str(year),'年後，存款金額會加倍')

67 年後，存款金額會加倍


# 帳號密碼程式

In [3]:
id = 'tony'
pwd = '1234'

while True:
    x = input('請輸入帳號:')
    y = input('請輸入密碼:')
    if(x==id and y==pwd):
        print('歡迎登入')
        break
    else:
        print('帳號/密碼輸入不正確')

請輸入帳號:aaa
請輸入密碼:bbb
帳號/密碼輸入不正確
請輸入帳號:tony
請輸入密碼:1234
歡迎登入


 # C#
    
 # Python

In [28]:
mylist = ['C#','Python','Java','C++']
for i in mylist:
    if i == 'Java':
        continue
    else:
            print(i)

C#
Python
C++


# 取10個亂數

In [11]:
import random
for i in range(0,10):
    print(random.random())

0.7799735399068399
0.34859979684179976
0.03629412959826195
0.8796314747978705
0.05353082690472222
0.12119514440202284
0.23035850527293888
0.7510378062468123
0.17622776064993828
0.5550742914777083


# 取10個 數字不超過2~8

In [22]:
for i in range(0,10):
    print(random.randint(1,9))

8
2
2
5
7
2
5
4
3
2


# 小遊戲

In [27]:
import random
number=random.randint(1,99)
while True:
    guess=input('請輸入1-99的數字(q離開):')
    if guess == 'q':
        print('離開遊戲')
        break
    else:
        if number==int(guess):
                print('恭喜，答對了')
                break
        else:
                print('答錯了')   

請輸入1-99的數字(q離開):22
答錯了
請輸入1-99的數字(q離開):q
離開遊戲


# numpy

In [1]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# nump套件ndarray型態，提供element-wise的操作

In [3]:
import numpy as np
a_ndarray=np.array([1,2,3,4,5])
print(a_ndarray*3)

[ 3  6  9 12 15]


# ndarrary維度 shape 資料型態

In [5]:
print(type(a_ndarray))
print(a_ndarray.ndim)
print(a_ndarray.shape)
print(a_ndarray.dtype)

<class 'numpy.ndarray'>
1
(5,)
int32


# 六個元素都為0的ID ndarray
# 12個元素都為0的2d ndarray
# 24個元素都未出始化的值
# 10個元素0-9的ID ndarray

In [6]:
z=np.zeros(6)  
print(z)                    
print(np.zeros((2,6)))      
print(np.empty((2,6,2)))    
print(np.arange(10))        

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[3.56043053e-307 1.60219306e-306]
  [7.56571288e-307 1.89146896e-307]
  [1.37961302e-306 1.05699242e-307]
  [8.01097889e-307 1.78020169e-306]
  [7.56601165e-307 1.02359984e-306]
  [1.33510679e-306 2.22522597e-306]]

 [[1.33511018e-306 6.23057689e-307]
  [7.56602524e-307 8.45559303e-307]
  [8.06612616e-308 6.89810244e-307]
  [1.22387550e-307 2.22522596e-306]
  [8.34423917e-308 1.11261162e-306]
  [1.78021527e-306 8.34426039e-308]]]
[0 1 2 3 4 5 6 7 8 9]


# ndarray的進階操作

In [7]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


# 維ndarray取值

In [10]:
my_2d_array = np.array([np.arange(0,5), np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:])  #第二列資料
print(my_2d_array[:,1])  #第二欄資料
print(my_2d_array[1,1])  #第二列第二航資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


# 假設有六個組別"Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"
# 其參加人數分別為56, 8, 19 ,14 ,6 ,71人

In [12]:
groups=["Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"]
ironman=[56, 8, 19 ,14 ,6 ,71]
groups_array=np.array(groups)
ironman_array=np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']
[56  8 19 14  6 71]


# 用人數去篩選組別

In [13]:
print(ironman_array >=10)
print(groups_array[(ironman_array) >=10])
print(groups_array != "自我挑戰組")
print(ironman_array[groups_array != "自我挑戰組"])

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']
[ True  True  True  True  True False]
[56  8 19 14  6]


# Ndarrary轉置

In [14]:
my_1d_array=np.arange(10)
print(my_1d_array)
my_2d_array=my_1d_array.reshape((2,5))
print(my_2d_array)
print(my_2d_array.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


# 有多少數字跟幾行幾列

In [15]:
print(np.arange(24).reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


# ndarray nan(空值)

In [17]:
nan_array=np.array([56,8,19,14,6, np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


# 第六章

# Pandas Data Frame

In [2]:
import pandas as pd

groups  = ["Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"]
ironmen = [59, 9, 19, 14, 6, 77]
ironmen_dict = {
                "groups": groups,
                "ironmen": ironmen
}
ironmen_df = pd.DataFrame(ironmen_dict)
ironmen_df

groups  ironmen
0  Modern Web       59
1      DevOps        9
2       Cloud       19
3    Big Data       14
4    Security        6
5       自我挑戰組       77

# ironmen各式語法

In [3]:
print(ironmen_df.ndim)
print(ironmen_df.shape)
print(ironmen_df.dtypes)

2
(6, 2)
groups     object
ironmen     int64
dtype: object


# 各種運算

In [4]:
print(ironmen_df.sum())
print(ironmen_df.ironmen.sum())
print(ironmen_df.mean())
print(ironmen_df.median())
print(ironmen_df.describe())

groups     Modern WebDevOpsCloudBig DataSecurity自我挑戰組
ironmen                                           184
dtype: object
184
ironmen    30.666667
dtype: float64
ironmen    16.5
dtype: float64
         ironmen
count   6.000000
mean   30.666667
std    29.803803
min     6.000000
25%    10.250000
50%    16.500000
75%    49.000000
max    77.000000


# 判斷那些組的組名是否為遺失值

In [6]:
import pandas as pd
import numpy as np
groups  = ["Modern Web","DevOps", np.nan, "Cloud","Big Data","Security","自我挑戰組"]
ironmen = [59, 9, 19, 14, 6, 77, np.nan]
ironmen_dict = {
                "groups": groups,
                "ironmen": ironmen
}
ironmen_df = pd.DataFrame(ironmen_dict)
print(ironmen_df.loc[:, "groups"].isnull())     #判斷那些組的組名是遺失值
print(ironmen_df.loc[:, "ironmen"].notnull())   #判斷那些組的組名不是遺失值

0    False
1    False
2     True
3    False
4    False
5    False
6    False
Name: groups, dtype: bool
0     True
1     True
2     True
3     True
4     True
5     True
6    False
Name: ironmen, dtype: bool


# 刪除空值

In [11]:
a=ironmen_df.dropna()    
a

groups  ironmen
0  Modern Web     59.0
1      DevOps      9.0
3       Cloud     14.0
4    Big Data      6.0
5    Security     77.0

# 空值補0

In [12]:
b=ironmen_df.fillna(0)   
b

groups  ironmen
0  Modern Web     59.0
1      DevOps      9.0
2           0     19.0
3       Cloud     14.0
4    Big Data      6.0
5    Security     77.0
6       自我挑戰組      0.0

# 空值補平均數

In [13]:
c=ironmen_df.ironmen.fillna(ironmen_df.ironmen.mean())  
c

0    59.000000
1     9.000000
2    19.000000
3    14.000000
4     6.000000
5    77.000000
6    30.666667
Name: ironmen, dtype: float64

# 建立 data frame

In [14]:
import pandas as pd

groups  = ["Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"]
ironmen = [59, 9, 19, 14, 6, 77]

ironmen_df = pd.DataFrame(ironmen, columns = ["ironmen"], index = groups)
ironmen_df.sort_index()

ironmen
Big Data         14
Cloud            19
DevOps            9
Modern Web       59
Security          6
自我挑戰組            77

# 第七章

# 雲端載入

In [3]:
import pandas as pd
ur1="https://storage.googleapis.com/2017_ithome_ironman/data/iris.csv"
iris_df = pd.read_csv(ur1)
iris_df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
iris_df['Sepal.Length'].median()

5.8

# 本地端載

In [26]:
import pandas as pd
iris_df = pd.read_csv('iris.csv')
iris_df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# 第八章

# 自訂函數

In [6]:
import math 

def circle(radius):
    area = radius * radius * math.pi
    return area

print(circle(10))

314.1592653589793


# 算圓面積

In [25]:
import math

def circle(radius):
    area = radius * radius * math.pi
    return area
r=input("請輸入圓的半徑:")
print("圓面積為:",circle(float(r)))

請輸入圓的半徑:12.5
圓面積為: 490.8738521234052


# example: exchange sort

In [13]:
import random

def exchange_sort(input_list):
    a=input_list
    for i in range(0, len(input_list)-1):
        for j in range(i+1, len(input_list)):
            if a[i]>a[j]:
                a[i], a[j]=a[j], a[i]
                return a
            
my_vector =random.sample (range(0,100), 10)
print(my_vector)
print(exchange_sort(my_vector))

[78, 60, 62, 33, 9, 4, 71, 45, 24, 3]
[60, 78, 62, 33, 9, 4, 71, 45, 24, 3]


# 排序

In [1]:
import random

def exchange_sort(input_list):
    a=input_list
    for i in range(0, len(input_list)-1):
        for j in range(i+1, len(input_list)):
            if a[i] > a[j]:
                a[i],  a[j]=a[j], a[i] 
    return a


def exchange_sort_r(input_list):
    a=input_list
    for i in range(0, len(input_list)-1):
        for j in range(i+1, len(input_list)):
            if a[i] < a[j]:
                a[i],  a[j]=a[j], a[i] 
    return a

my_vector = random.sample (range(0,100), 10)
print(my_vector)
print(exchange_sort(my_vector))
print(exchange_sort_r(my_vector))

[34, 58, 24, 84, 4, 1, 16, 77, 56, 26]
[1, 4, 16, 24, 26, 34, 56, 58, 77, 84]
[84, 77, 58, 56, 34, 26, 24, 16, 4, 1]


# python的lambda函數

In [2]:
def circle(radius):
    return radius * radius * 3.14

print(circle(10))

314.0


# max

In [3]:
def max(m,n):
    return m if m > n else n
print(max(10,3))

10


# lambda

In [4]:
#lambda
max = lambda m,n: m if m>n else n
print(max(10,3))

10


# lamda寫法

In [5]:
# list *5
a=[1,2,3,4,5]
print(a*5)
#numbpy *5
import numpy as np
b=np.array(a)
print(b*5)
#lamda寫法
c=list(map(lambda x: x*5, a)) #map(function, data)
print(c)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]
[5, 10, 15, 20, 25]


# 錯誤處理 try:except:

In [6]:
def circle(radius):
    try:
        return radius * radius * 3.14
    except:
        return"請輸入數值"
    
print(circle(10))
print(circle('十'))

314.0
請輸入數值
